package main

//
// an indexing application "plugin" for MapReduce.
//
// go build -buildmode=plugin indexer.go
//

import (
	"fmt"
	"sort"
	"strings"
	"unicode"

	"6.824/mr"
)

// The mapping function is called once for each piece of the input.
// In this framework, the key is the name of the file that is being processed,
// and the value is the file's contents. The return value should be a slice of
// key/value pairs, each represented by a mr.KeyValue.
// 映射函数对于输入的每个部分调用一次。
// 在这个框架中，键是正在处理的文件的名称，
// 这个值是文件的内容。返回值应该是
// key/value对，每个都由mr.KeyValue表示。
func Map(document string, value string) (res []mr.KeyValue) {
	m := make(map[string]bool)
	// 对文本进行单词划分
	words := strings.FieldsFunc(value, func(x rune) bool { return !unicode.IsLetter(x) })
	for _, w := range words {
		m[w] = true
	}
	for w := range m {
		kv := mr.KeyValue{w, document}
		res = append(res, kv)
	}
	return
}

// The reduce function is called once for each key generated by Map, with a
// list of that key's string value (merged across all inputs). The return value
// should be a single output value for that key.
// 对于Map生成的每个键调用一次reduce函数，使用
// 该键的字符串值的列表(跨所有输入合并)。返回值
// 应该是该键的单个输出值。
func Reduce(key string, values []string) string {
	sort.Strings(values)
	return fmt.Sprintf("%d %s", len(values), strings.Join(values, ","))
}
